import { useState } from 'react'
import {
  ChevronDown,
  ChevronUp,
  FileText,
  CheckCircle,
  XCircle,
  AlertCircle,
  Sparkles,
  HelpCircle,
} from 'lucide-react'
import { StatusBadge } from '../common/StatusBadge'
import { EvidencePanel } from './EvidencePanel'
import type { SchemeResult } from '../../types/eligibility'

interface SchemeCardProps {
  scheme: SchemeResult
}

export function SchemeCard({ scheme }: SchemeCardProps) {
  const [showEvidence, setShowEvidence] = useState(false)

  const matchedRules = scheme?.matchedRules || []
  const failedRules = scheme?.failedRules || []
  const missingInfo = scheme?.missingInformation || []
  const documents = scheme?.requiredDocuments || []
  const evidence = scheme?.evidence || []

  const isNeedsInfo = scheme?.status === 'NEEDS_MORE_INFORMATION'

  return (
    <article
      className={`scheme-card scheme-card-${(scheme?.status || 'unknown').toLowerCase()}`}
      id={`scheme-card-${scheme?.schemeId}`}
    >
      <header className="scheme-card-top">
        <div className="scheme-header-left">
          <span className="scheme-id-badge">{scheme?.schemeId || 'SCHEME'}</span>
          <h3 className="scheme-title">{scheme?.schemeName || 'Unnamed Scheme'}</h3>
        </div>
        <StatusBadge status={scheme?.status || 'NEEDS_MORE_INFORMATION'} />
      </header>

      {scheme?.explanation && (
        <div className="scheme-explanation-box">
          <p className="scheme-explanation-text">
            {scheme.explanationSource === 'llm' && (
              <span className="ai-tag" title="Explanation generated by AI reasoning">
                <Sparkles size={11} /> AI Summary
              </span>
            )}
            {scheme.explanation}
          </p>
        </div>
      )}

      {/* Missing Information - Highlighted for NEEDS_MORE_INFORMATION */}
      {missingInfo.length > 0 && (
        <div
          className={`card-section missing-info-section ${
            isNeedsInfo ? 'missing-info-highlighted' : ''
          }`}
        >
          <div className="section-subtitle-row">
            <AlertCircle size={14} className="icon-warning" />
            <span className="section-subtitle">Information Needed</span>
          </div>
          <ul className="missing-info-list">
            {missingInfo.map((info, idx) => (
              <li key={`missing-${idx}`} className="missing-info-item">
                {info}
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Matched Rules */}
      {matchedRules.length > 0 && (
        <div className="card-section matched-rules-section">
          <div className="section-subtitle-row">
            <CheckCircle size={14} className="icon-success" />
            <span className="section-subtitle">
              Matched Conditions ({matchedRules.length})
            </span>
          </div>
          <ul className="rules-list rules-list-matched">
            {matchedRules.map((rule, idx) => (
              <li key={rule.ruleId || `match-${idx}`} className="rule-item rule-item-matched">
                <strong>{rule.ruleId}:</strong> <span>{rule.reason}</span>
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Failed Rules */}
      {failedRules.length > 0 && (
        <div className="card-section failed-rules-section">
          <div className="section-subtitle-row">
            <XCircle size={14} className="icon-danger" />
            <span className="section-subtitle">
              Unmet Conditions ({failedRules.length})
            </span>
          </div>
          <ul className="rules-list rules-list-failed">
            {failedRules.map((rule, idx) => (
              <li key={rule.ruleId || `fail-${idx}`} className="rule-item rule-item-failed">
                <strong>{rule.ruleId}:</strong> <span>{rule.reason}</span>
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Required Documents */}
      {documents.length > 0 && (
        <div className="card-section documents-section">
          <div className="section-subtitle-row">
            <FileText size={14} className="icon-muted" />
            <span className="section-subtitle">Required Documents ({documents.length})</span>
          </div>
          <div className="document-chips">
            {documents.map((doc, idx) => (
              <span key={`doc-${idx}`} className="doc-chip">
                {doc}
              </span>
            ))}
          </div>
        </div>
      )}

      {/* Why? / Evidence Expandable Section */}
      <div className="scheme-card-evidence-toggle">
        <button
          type="button"
          className="evidence-toggle-button"
          onClick={() => setShowEvidence((prev) => !prev)}
          aria-expanded={showEvidence}
        >
          <span className="toggle-label-with-icon">
            <HelpCircle size={14} />
            <strong>Why? / Evidence</strong>
            <span className="evidence-count">({evidence.length} clauses)</span>
          </span>
          {showEvidence ? <ChevronUp size={16} /> : <ChevronDown size={16} />}
        </button>

        {showEvidence && (
          <div className="evidence-collapsible-content">
            <EvidencePanel
              evidence={evidence}
              matchedRules={matchedRules}
              failedRules={failedRules}
            />
          </div>
        )}
      </div>
    </article>
  )
}